### ISSUE TITLE
Dashpanel Address Link Text Missing Last Digit

### ISSUE THREAD

**Issue by BTCAlchemist** [otocorp/OtoCo-Gatsby#6]
In the dashpanel (https://otoco.io/dashboard/), the Manager address and the series LLC address have link text that starts with 0x and ends with four characters. These four characters are not the last four characters of the Ethereum address and are missing the final character in the address (I am not including a screenshot of a specific example for privacy reasons).

**Comment by filipesoccol** [comment]
Already corrected and redeployed at https://github.com/otocorp/OtoCo-Gatsby/commit/944552a6ceb62ff4ff1aef5e31792123be42a423. Thank you @BTCAlchemist!
