### ISSUE TITLE
Spinup Page "Next" Button Does Not Change Back to "Check" 

### ISSUE THREAD

**Issue by BTCAlchemist** [otocorp/OtoCo-Gatsby#7]
On the spinup page (https://otoco.io/spinup/), after entering text and clicking the "Check" button, if I edit the company name search field, the button still says "Next" instead of "Check". Button should automatically detect if the search field gets modified and change its action back to "Check".

'asdfa' search is available
![image](https://user-images.githubusercontent.com/56145569/103465350-8cea6b80-4cef-11eb-946f-65f01729016d.png)

'asdf' search is not available but button does not update
![image](https://user-images.githubusercontent.com/56145569/103465324-3715c380-4cef-11eb-82c0-9d98f5044a95.png)

**Comment by filipesoccol** [comment]
Thank you for your contribution @BTCAlchemist! Bug already corrected and app redeployed. https://github.com/otocorp/OtoCo-Gatsby/commit/944552a6ceb62ff4ff1aef5e31792123be42a423
